import type { Question } from '../types';

export const questions: Question[] = [
  { id: 'q26-1', lesson: 26, part: 'A', minutes: 3,
    prompt: 'Tell me about a production incident you handled.',
    strongAnswerPoints: ['Containment first (rollback, flag, failover), then communication to stakeholders.', 'Diagnosis with evidence: logs, metrics, recent changes.', 'Safe recovery and verification; root cause separated from contributing factors.', 'Concrete prevention: tests, alerts, runbook, blameless review.'],
    redFlags: ['Blames a person', 'No prevention step', 'Hero story with no communication'],
    followUps: ['What would you do differently?'] },
  { id: 'q26-2', lesson: 26, part: 'A', minutes: 3,
    prompt: 'Describe a technical disagreement with a colleague or lead and how it was resolved.',
    strongAnswerPoints: ['States the other view fairly.', 'Uses evidence and agreed criteria (prototype, benchmark, risk).', 'Disagree-and-commit or changed own mind; the relationship stayed intact.'],
    redFlags: ['Won by seniority or persistence', 'Dismisses the other person'] },
  { id: 'q26-3', lesson: 26, part: 'A', minutes: 3,
    prompt: 'Tell me about a time you were under pressure to deliver and had to decide what to cut or delay.',
    strongAnswerPoints: ['Clarified the goal and constraints with stakeholders.', 'Prioritised by risk and value; made trade-offs visible.', 'Communicated early; outcome and what you learned.'],
    redFlags: ['Silently cut quality', 'Worked unsustainable hours as the only answer'] },
  { id: 'q26-4', lesson: 26, part: 'B', minutes: 3,
    prompt: 'Tell me about a time you mentored someone or raised the quality bar on your team.',
    strongAnswerPoints: ['Specific mechanism: review checklist, pairing, test strategy, template.', 'Kind, specific feedback.', 'Team-level result such as fewer defects or faster onboarding.'],
    redFlags: ['Only describes own output', 'No measurable effect'] },
  { id: 'q26-5', lesson: 26, part: 'B', minutes: 3,
    prompt: 'Describe a time you stopped or delayed a release, or raised a security or risk concern.',
    strongAnswerPoints: ['Gathered evidence and quantified impact.', 'Offered options (delay, flag, reduced scope) and used the right escalation path.', 'Respectful about the pressure to ship; made the safe path easier afterwards.'],
    redFlags: ['Went around people', 'Raised a concern without evidence or alternatives'] },
  { id: 'q26-6', lesson: 26, part: 'B', minutes: 2,
    prompt: 'Why Citi, and why Enterprise Risk Technology?',
    strongAnswerPoints: ['The problem: risk systems where correctness, auditability and resilience matter.', 'Specific fit from your experience.', 'Honest about the Angular and Java gap and how you are closing it.'],
    redFlags: ['Generic flattery about the brand', 'Cannot say what the team does'] },
];
